server:
  port: 8080
logging:
  level:
    root: info
    org.springframework.security: debug
  file: TacoCloud.log
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tacocloud
    username: root
    password: sunmood
    driver-class-name: com.mysql.jdbc.Driver
    data: classpath:data.sql
    schema: classpath:schema.sql
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
